In [91]:
from path import Path
import pandas as pd
import numpy as np
import re

In [92]:
# reading csv file
data = Path('Resources/Coviddataset.csv')
covid_dataset_df = pd.read_csv(data)
covid_dataset_df

,iso_code,continent,location,date,population,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-02-24,39835428.0,5.0,5.0,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-02-25,39835428.0,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-02-26,39835428.0,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-02-27,39835428.0,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-02-28,39835428.0,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153395,ZWE,Africa,Zimbabwe,2022-01-05,15092171.0,219057.0,1379.0,1644.143,5092.0,14.0,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
153396,ZWE,Africa,Zimbabwe,2022-01-06,15092171.0,220178.0,1121.0,1207.143,5108.0,16.0,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
153397,ZWE,Africa,Zimbabwe,2022-01-07,15092171.0,221282.0,1104.0,1146.286,5136.0,28.0,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
153398,ZWE,Africa,Zimbabwe,2022-01-08,15092171.0,221918.0,636.0,1100.571,5148.0,12.0,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
153399,ZWE,Africa,Zimbabwe,2022-01-09,15092171.0,221918.0,NaN,NaN,5148.0,NaN,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN

In [93]:
#checking number of rows and columns
covid_dataset_df.shape

(153400, 67)

In [94]:
# checking data type
covid_dataset_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 153400 entries, 0 to 153399
Data columns (total 67 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   iso_code                                    153400 non-null  object
 1   continent                                   144159 non-null  object
 2   location                                    153400 non-null  object
 3   date                                        153400 non-null  object
 4   population                                  152380 non-null  float64
 5   total_cases                                 150750 non-null  float64
 6   new_cases                                   150631 non-null  float64
 7   new_cases_smoothed                          149480 non-null  float64
 8   total_deaths                                133494 non-null  float64
 9   new_deaths                                  133649 non-null  float64
 10  new_deaths_smoothed                         133517 non-null  float64
 11  total_cases_per_million                     150047 non-null  float64
 12  new_cases_per_million                       149928 non-null  float64
 13  new_cases_smoothed_per_million              148782 non-null  float64
 14  total_deaths_per_million                    132804 non-null  float64
 15  new_deaths_per_million                      132959 non-null  float64
 16  new_deaths_smoothed_per_million             132827 non-null  float64
 17  reproduction_rate                           114970 non-null  float64
 18  icu_patients                                19345 non-null   float64
 19  icu_patients_per_million                    19345 non-null   float64
 20  hosp_patients                               21314 non-null   float64
 21  hosp_patients_per_million                   21314 non-null   float64
 22  weekly_icu_admissions                       4343 non-null    float64
 23  weekly_icu_admissions_per_million           4343 non-null    float64
 24  weekly_hosp_admissions                      8702 non-null    float64
 25  weekly_hosp_admissions_per_million          8702 non-null    float64
 26  new_tests                                   60733 non-null   float64
 27  total_tests                                 62146 non-null   float64
 28  total_tests_per_thousand                    62146 non-null   float64
 29  new_tests_per_thousand                      60733 non-null   float64
 30  new_tests_smoothed                          74236 non-null   float64
 31  new_tests_smoothed_per_thousand             73535 non-null   float64
 32  positive_rate                               69318 non-null   float64
 33  tests_per_case                              68655 non-null   float64
 34  tests_units                                 75706 non-null   object
 35  total_vaccinations                          39841 non-null   float64
 36  people_vaccinated                           38146 non-null   float64
 37  people_fully_vaccinated                     35286 non-null   float64
 38  total_boosters                              12740 non-null   float64
 39  new_vaccinations                            33098 non-null   float64
 40  new_vaccinations_smoothed                   72013 non-null   float64
 41  total_vaccinations_per_hundred              39841 non-null   float64
 42  people_vaccinated_per_hundred               38146 non-null   float64
 43  people_fully_vaccinated_per_hundred         35286 non-null   float64
 44  total_boosters_per_hundred                  12740 non-null   float64
 45  new_vaccinations_smoothed_per_million       72013 non-null   float64
 46  new_people_vaccinated_smoothed              70798 non-null   float64
 47  new_people_vaccinated_smoothed_per_hundred  70798 non-null   float64
 48  stringency_index                            119759 non-null  float64
 49  population_density                          136547 non-null  float64
 50  median_age                                  127424 non-null  float64
 51  aged_65_older                               126040 non-null  float64
 52  aged_70_older                               126740 non-null  float64
 53  gdp_per_capita                              127838 non-null  float64
 54  extreme_poverty                             84383 non-null   float64
 55  cardiovasc_death_rate                       126426 non-null  float64
 56  diabetes_prevalence                         132907 non-null  float64
 57  female_smokers                              97923 non-null   float64
 58  male_smokers                                96513 non-null   float64
 59  handwashing_facilities                      63317 non-null   float64
 60  hospital_beds_per_thousand                  114217 non-null  float64
 61  life_expectancy                             143168 non-null  float64
 62  human_development_index                     125901 non-null  float64
 63  excess_mortality_cumulative_absolute        5234 non-null    float64
 64  excess_mortality_cumulative                 5234 non-null    float64
 65  excess_mortality                            5234 non-null    float64
 66  excess_mortality_cumulative_per_million     5234 non-null    float64
dtypes: float64(62), object(5)
memory usage: 78.4+ MB

In [95]:
#Checking for null values
for column in covid_dataset_df.columns:
    print(f"Column {column} has {covid_dataset_df[column].isnull().sum()} null values")

Column iso_code has 0 null values
Column continent has 9241 null values
Column location has 0 null values
Column date has 0 null values
Column population has 1020 null values
Column total_cases has 2650 null values
Column new_cases has 2769 null values
Column new_cases_smoothed has 3920 null values
Column total_deaths has 19906 null values
Column new_deaths has 19751 null values
Column new_deaths_smoothed has 19883 null values
Column total_cases_per_million has 3353 null values
Column new_cases_per_million has 3472 null values
Column new_cases_smoothed_per_million has 4618 null values
Column total_deaths_per_million has 20596 null values
Column new_deaths_per_million has 20441 null values
Column new_deaths_smoothed_per_million has 20573 null values
Column reproduction_rate has 38430 null values
Column icu_patients has 134055 null values
Column icu_patients_per_million has 134055 null values
Column hosp_patients has 132086 null values
Column hosp_patients_per_million has 132086 null values
Column weekly_icu_admissions has 149057 null values
Column weekly_icu_admissions_per_million has 149057 null values
Column weekly_hosp_admissions has 144698 null values
Column weekly_hosp_admissions_per_million has 144698 null values
Column new_tests has 92667 null values
Column total_tests has 91254 null values
Column total_tests_per_thousand has 91254 null values
Column new_tests_per_thousand has 92667 null values
Column new_tests_smoothed has 79164 null values
Column new_tests_smoothed_per_thousand has 79865 null values
Column positive_rate has 84082 null values
Column tests_per_case has 84745 null values
Column tests_units has 77694 null values
Column total_vaccinations has 113559 null values
Column people_vaccinated has 115254 null values
Column people_fully_vaccinated has 118114 null values
Column total_boosters has 140660 null values
Column new_vaccinations has 120302 null values
Column new_vaccinations_smoothed has 81387 null values
Column total_vaccinations_per_hundred has 113559 null values
Column people_vaccinated_per_hundred has 115254 null values
Column people_fully_vaccinated_per_hundred has 118114 null values
Column total_boosters_per_hundred has 140660 null values
Column new_vaccinations_smoothed_per_million has 81387 null values
Column new_people_vaccinated_smoothed has 82602 null values
Column new_people_vaccinated_smoothed_per_hundred has 82602 null values
Column stringency_index has 33641 null values
Column population_density has 16853 null values
Column median_age has 25976 null values
Column aged_65_older has 27360 null values
Column aged_70_older has 26660 null values
Column gdp_per_capita has 25562 null values
Column extreme_poverty has 69017 null values
Column cardiovasc_death_rate has 26974 null values
Column diabetes_prevalence has 20493 null values
Column female_smokers has 55477 null values
Column male_smokers has 56887 null values
Column handwashing_facilities has 90083 null values
Column hospital_beds_per_thousand has 39183 null values
Column life_expectancy has 10232 null values
Column human_development_index has 27499 null values
Column excess_mortality_cumulative_absolute has 148166 null values
Column excess_mortality_cumulative has 148166 null values
Column excess_mortality has 148166 null values
Column excess_mortality_cumulative_per_million has 148166 null values

In [96]:
# checking on columns unique values (iso_code,continent and location)
for column in covid_dataset_df.columns:
    print(f"{column}{covid_dataset_df[column].unique()}")

iso_code['AFG' 'OWID_AFR' 'ALB' 'DZA' 'AND' 'AGO' 'AIA' 'ATG' 'ARG' 'ARM' 'ABW'
 'OWID_ASI' 'AUS' 'AUT' 'AZE' 'BHS' 'BHR' 'BGD' 'BRB' 'BLR' 'BEL' 'BLZ'
 'BEN' 'BMU' 'BTN' 'BOL' 'BES' 'BIH' 'BWA' 'BRA' 'VGB' 'BRN' 'BGR' 'BFA'
 'BDI' 'KHM' 'CMR' 'CAN' 'CPV' 'CYM' 'CAF' 'TCD' 'CHL' 'CHN' 'COL' 'COM'
 'COG' 'COK' 'CRI' 'CIV' 'HRV' 'CUB' 'CUW' 'CYP' 'CZE' 'COD' 'DNK' 'DJI'
 'DMA' 'DOM' 'ECU' 'EGY' 'SLV' 'GNQ' 'ERI' 'EST' 'SWZ' 'ETH' 'OWID_EUR'
 'OWID_EUN' 'FRO' 'FLK' 'FJI' 'FIN' 'FRA' 'PYF' 'GAB' 'GMB' 'GEO' 'DEU'
 'GHA' 'GIB' 'GRC' 'GRL' 'GRD' 'GTM' 'GGY' 'GIN' 'GNB' 'GUY' 'HTI'
 'OWID_HIC' 'HND' 'HKG' 'HUN' 'ISL' 'IND' 'IDN' 'OWID_INT' 'IRN' 'IRQ'
 'IRL' 'IMN' 'ISR' 'ITA' 'JAM' 'JPN' 'JEY' 'JOR' 'KAZ' 'KEN' 'KIR'
 'OWID_KOS' 'KWT' 'KGZ' 'LAO' 'LVA' 'LBN' 'LSO' 'LBR' 'LBY' 'LIE' 'LTU'
 'OWID_LIC' 'OWID_LMC' 'LUX' 'MAC' 'MDG' 'MWI' 'MYS' 'MDV' 'MLI' 'MLT'
 'MHL' 'MRT' 'MUS' 'MEX' 'FSM' 'MDA' 'MCO' 'MNG' 'MNE' 'MSR' 'MAR' 'MOZ'
 'MMR' 'NAM' 'NRU' 'NPL' 'NLD' 'NCL' 'NZL' 'NIC' 'NER' 'NGA' 'NIU'
 'OWID_NAM' 'MKD' 'OWID_CYN' 'NOR' 'OWID_OCE' 'OMN' 'PAK' 'PLW' 'PSE'
 'PAN' 'PNG' 'PRY' 'PER' 'PHL' 'PCN' 'POL' 'PRT' 'QAT' 'ROU' 'RUS' 'RWA'
 'SHN' 'KNA' 'LCA' 'SPM' 'VCT' 'WSM' 'SMR' 'STP' 'SAU' 'SEN' 'SRB' 'SYC'
 'SLE' 'SGP' 'SXM' 'SVK' 'SVN' 'SLB' 'SOM' 'ZAF' 'OWID_SAM' 'KOR' 'SSD'
 'ESP' 'LKA' 'SDN' 'SUR' 'SWE' 'CHE' 'SYR' 'TWN' 'TJK' 'TZA' 'THA' 'TLS'
 'TGO' 'TKL' 'TON' 'TTO' 'TUN' 'TUR' 'TKM' 'TCA' 'TUV' 'UGA' 'UKR' 'ARE'
 'GBR' 'USA' 'OWID_UMC' 'URY' 'UZB' 'VUT' 'VAT' 'VEN' 'VNM' 'WLF'
 'OWID_WRL' 'YEM' 'ZMB' 'ZWE']
continent['Asia' nan 'Europe' 'Africa' 'North America' 'South America' 'Oceania']
location['Afghanistan' 'Africa' 'Albania' 'Algeria' 'Andorra' 'Angola' 'Anguilla'
 'Antigua and Barbuda' 'Argentina' 'Armenia' 'Aruba' 'Asia' 'Australia'
 'Austria' 'Azerbaijan' 'Bahamas' 'Bahrain' 'Bangladesh' 'Barbados'
 'Belarus' 'Belgium' 'Belize' 'Benin' 'Bermuda' 'Bhutan' 'Bolivia'
 'Bonaire Sint Eustatius and Saba' 'Bosnia and Herzegovina' 'Botswana'
 'Brazil' 'British Virgin Islands' 'Brunei' 'Bulgaria' 'Burkina Faso'
 'Burundi' 'Cambodia' 'Cameroon' 'Canada' 'Cape Verde' 'Cayman Islands'
 'Central African Republic' 'Chad' 'Chile' 'China' 'Colombia' 'Comoros'
 'Congo' 'Cook Islands' 'Costa Rica' "Cote d'Ivoire" 'Croatia' 'Cuba'
 'Curacao' 'Cyprus' 'Czechia' 'Democratic Republic of Congo' 'Denmark'
 'Djibouti' 'Dominica' 'Dominican Republic' 'Ecuador' 'Egypt'
 'El Salvador' 'Equatorial Guinea' 'Eritrea' 'Estonia' 'Eswatini'
 'Ethiopia' 'Europe' 'European Union' 'Faeroe Islands' 'Falkland Islands'
 'Fiji' 'Finland' 'France' 'French Polynesia' 'Gabon' 'Gambia' 'Georgia'
 'Germany' 'Ghana' 'Gibraltar' 'Greece' 'Greenland' 'Grenada' 'Guatemala'
 'Guernsey' 'Guinea' 'Guinea-Bissau' 'Guyana' 'Haiti' 'High income'
 'Honduras' 'Hong Kong' 'Hungary' 'Iceland' 'India' 'Indonesia'
 'International' 'Iran' 'Iraq' 'Ireland' 'Isle of Man' 'Israel' 'Italy'
 'Jamaica' 'Japan' 'Jersey' 'Jordan' 'Kazakhstan' 'Kenya' 'Kiribati'
 'Kosovo' 'Kuwait' 'Kyrgyzstan' 'Laos' 'Latvia' 'Lebanon' 'Lesotho'
 'Liberia' 'Libya' 'Liechtenstein' 'Lithuania' 'Low income'
 'Lower middle income' 'Luxembourg' 'Macao' 'Madagascar' 'Malawi'
 'Malaysia' 'Maldives' 'Mali' 'Malta' 'Marshall Islands' 'Mauritania'
 'Mauritius' 'Mexico' 'Micronesia (country)' 'Moldova' 'Monaco' 'Mongolia'
 'Montenegro' 'Montserrat' 'Morocco' 'Mozambique' 'Myanmar' 'Namibia'
 'Nauru' 'Nepal' 'Netherlands' 'New Caledonia' 'New Zealand' 'Nicaragua'
 'Niger' 'Nigeria' 'Niue' 'North America' 'North Macedonia'
 'Northern Cyprus' 'Norway' 'Oceania' 'Oman' 'Pakistan' 'Palau'
 'Palestine' 'Panama' 'Papua New Guinea' 'Paraguay' 'Peru' 'Philippines'
 'Pitcairn' 'Poland' 'Portugal' 'Qatar' 'Romania' 'Russia' 'Rwanda'
 'Saint Helena' 'Saint Kitts and Nevis' 'Saint Lucia'
 'Saint Pierre and Miquelon' 'Saint Vincent and the Grenadines' 'Samoa'
 'San Marino' 'Sao Tome and Principe' 'Saudi Arabia' 'Senegal' 'Serbia'
 'Seychelles' 'Sierra Leone' 'Singapore' 'Sint Maarten (Dutch part)'
 'Slovakia' 'Slovenia' 'Solomon Islands' 'Somalia' 'South Africa'
 'South America' 'South Korea' 'South Sudan' 'Spain' 'Sri Lanka' 'Sudan'
 'Suriname' 'Sweden' 'Switzerland' 'Syria' 'Taiwan' 'Tajikistan'
 'Tanzania' 'Thailand' 'Timor' 'Togo' 'Tokelau' 'Tonga'
 'Trinidad and Tobago' 'Tunisia' 'Turkey' 'Turkmenistan'
 'Turks and Caicos Islands' 'Tuvalu' 'Uganda' 'Ukraine'
 'United Arab Emirates' 'United Kingdom' 'United States'
 'Upper middle income' 'Uruguay' 'Uzbekistan' 'Vanuatu' 'Vatican'
 'Venezuela' 'Vietnam' 'Wallis and Futuna' 'World' 'Yemen' 'Zambia'
 'Zimbabwe']
date['2020-02-24' '2020-02-25' '2020-02-26' '2020-02-27' '2020-02-28'
 '2020-02-29' '2020-03-01' '2020-03-02' '2020-03-03' '2020-03-04'
 '2020-03-05' '2020-03-06' '2020-03-07' '2020-03-08' '2020-03-09'
 '2020-03-10' '2020-03-11' '2020-03-12' '2020-03-13' '2020-03-14'
 '2020-03-15' '2020-03-16' '2020-03-17' '2020-03-18' '2020-03-19'
 '2020-03-20' '2020-03-21' '2020-03-22' '2020-03-23' '2020-03-24'
 '2020-03-25' '2020-03-26' '2020-03-27' '2020-03-28' '2020-03-29'
 '2020-03-30' '2020-03-31' '2020-04-01' '2020-04-02' '2020-04-03'
 '2020-04-04' '2020-04-05' '2020-04-06' '2020-04-07' '2020-04-08'
 '2020-04-09' '2020-04-10' '2020-04-11' '2020-04-12' '2020-04-13'
 '2020-04-14' '2020-04-15' '2020-04-16' '2020-04-17' '2020-04-18'
 '2020-04-19' '2020-04-20' '2020-04-21' '2020-04-22' '2020-04-23'
 '2020-04-24' '2020-04-25' '2020-04-26' '2020-04-27' '2020-04-28'
 '2020-04-29' '2020-04-30' '2020-05-01' '2020-05-02' '2020-05-03'
 '2020-05-04' '2020-05-05' '2020-05-06' '2020-05-07' '2020-05-08'
 '2020-05-09' '2020-05-10' '2020-05-11' '2020-05-12' '2020-05-13'
 '2020-05-14' '2020-05-15' '2020-05-16' '2020-05-17' '2020-05-18'
 '2020-05-19' '2020-05-20' '2020-05-21' '2020-05-22' '2020-05-23'
 '2020-05-24' '2020-05-25' '2020-05-26' '2020-05-27' '2020-05-28'
 '2020-05-29' '2020-05-30' '2020-05-31' '2020-06-01' '2020-06-02'
 '2020-06-03' '2020-06-04' '2020-06-05' '2020-06-06' '2020-06-07'
 '2020-06-08' '2020-06-09' '2020-06-10' '2020-06-11' '2020-06-12'
 '2020-06-13' '2020-06-14' '2020-06-15' '2020-06-16' '2020-06-17'
 '2020-06-18' '2020-06-19' '2020-06-20' '2020-06-21' '2020-06-22'
 '2020-06-23' '2020-06-24' '2020-06-25' '2020-06-26' '2020-06-27'
 '2020-06-28' '2020-06-29' '2020-06-30' '2020-07-01' '2020-07-02'
 '2020-07-03' '2020-07-04' '2020-07-05' '2020-07-06' '2020-07-07'
 '2020-07-08' '2020-07-09' '2020-07-10' '2020-07-11' '2020-07-12'
 '2020-07-13' '2020-07-14' '2020-07-15' '2020-07-16' '2020-07-17'
 '2020-07-18' '2020-07-19' '2020-07-20' '2020-07-21' '2020-07-22'
 '2020-07-23' '2020-07-24' '2020-07-25' '2020-07-26' '2020-07-27'
 '2020-07-28' '2020-07-29' '2020-07-30' '2020-07-31' '2020-08-01'
 '2020-08-02' '2020-08-03' '2020-08-04' '2020-08-05' '2020-08-06'
 '2020-08-07' '2020-08-08' '2020-08-09' '2020-08-10' '2020-08-11'
 '2020-08-12' '2020-08-13' '2020-08-14' '2020-08-15' '2020-08-16'
 '2020-08-17' '2020-08-18' '2020-08-19' '2020-08-20' '2020-08-21'
 '2020-08-22' '2020-08-23' '2020-08-24' '2020-08-25' '2020-08-26'
 '2020-08-27' '2020-08-28' '2020-08-29' '2020-08-30' '2020-08-31'
 '2020-09-01' '2020-09-02' '2020-09-03' '2020-09-04' '2020-09-05'
 '2020-09-06' '2020-09-07' '2020-09-08' '2020-09-09' '2020-09-10'
 '2020-09-11' '2020-09-12' '2020-09-13' '2020-09-14' '2020-09-15'
 '2020-09-16' '2020-09-17' '2020-09-18' '2020-09-19' '2020-09-20'
 '2020-09-21' '2020-09-22' '2020-09-23' '2020-09-24' '2020-09-25'
 '2020-09-26' '2020-09-27' '2020-09-28' '2020-09-29' '2020-09-30'
 '2020-10-01' '2020-10-02' '2020-10-03' '2020-10-04' '2020-10-05'
 '2020-10-06' '2020-10-07' '2020-10-08' '2020-10-09' '2020-10-10'
 '2020-10-11' '2020-10-12' '2020-10-13' '2020-10-14' '2020-10-15'
 '2020-10-16' '2020-10-17' '2020-10-18' '2020-10-19' '2020-10-20'
 '2020-10-21' '2020-10-22' '2020-10-23' '2020-10-24' '2020-10-25'
 '2020-10-26' '2020-10-27' '2020-10-28' '2020-10-29' '2020-10-30'
 '2020-10-31' '2020-11-01' '2020-11-02' '2020-11-03' '2020-11-04'
 '2020-11-05' '2020-11-06' '2020-11-07' '2020-11-08' '2020-11-09'
 '2020-11-10' '2020-11-11' '2020-11-12' '2020-11-13' '2020-11-14'
 '2020-11-15' '2020-11-16' '2020-11-17' '2020-11-18' '2020-11-19'
 '2020-11-20' '2020-11-21' '2020-11-22' '2020-11-23' '2020-11-24'
 '2020-11-25' '2020-11-26' '2020-11-27' '2020-11-28' '2020-11-29'
 '2020-11-30' '2020-12-01' '2020-12-02' '2020-12-03' '2020-12-04'
 '2020-12-05' '2020-12-06' '2020-12-07' '2020-12-08' '2020-12-09'
 '2020-12-10' '2020-12-11' '2020-12-12' '2020-12-13' '2020-12-14'
 '2020-12-15' '2020-12-16' '2020-12-17' '2020-12-18' '2020-12-19'
 '2020-12-20' '2020-12-21' '2020-12-22' '2020-12-23' '2020-12-24'
 '2020-12-25' '2020-12-26' '2020-12-27' '2020-12-28' '2020-12-29'
 '2020-12-30' '2020-12-31' '2021-01-01' '2021-01-02' '2021-01-03'
 '2021-01-04' '2021-01-05' '2021-01-06' '2021-01-07' '2021-01-08'
 '2021-01-09' '2021-01-10' '2021-01-11' '2021-01-12' '2021-01-13'
 '2021-01-14' '2021-01-15' '2021-01-16' '2021-01-17' '2021-01-18'
 '2021-01-19' '2021-01-20' '2021-01-21' '2021-01-22' '2021-01-23'
 '2021-01-24' '2021-01-25' '2021-01-26' '2021-01-27' '2021-01-28'
 '2021-01-29' '2021-01-30' '2021-01-31' '2021-02-01' '2021-02-02'
 '2021-02-03' '2021-02-04' '2021-02-05' '2021-02-06' '2021-02-07'
 '2021-02-08' '2021-02-09' '2021-02-10' '2021-02-11' '2021-02-12'
 '2021-02-13' '2021-02-14' '2021-02-15' '2021-02-16' '2021-02-17'
 '2021-02-18' '2021-02-19' '2021-02-20' '2021-02-21' '2021-02-22'
 '2021-02-23' '2021-02-24' '2021-02-25' '2021-02-26' '2021-02-27'
 '2021-02-28' '2021-03-01' '2021-03-02' '2021-03-03' '2021-03-04'
 '2021-03-05' '2021-03-06' '2021-03-07' '2021-03-08' '2021-03-09'
 '2021-03-10' '2021-03-11' '2021-03-12' '2021-03-13' '2021-03-14'
 '2021-03-15' '2021-03-16' '2021-03-17' '2021-03-18' '2021-03-19'
 '2021-03-20' '2021-03-21' '2021-03-22' '2021-03-23' '2021-03-24'
 '2021-03-25' '2021-03-26' '2021-03-27' '2021-03-28' '2021-03-29'
 '2021-03-30' '2021-03-31' '2021-04-01' '2021-04-02' '2021-04-03'
 '2021-04-04' '2021-04-05' '2021-04-06' '2021-04-07' '2021-04-08'
 '2021-04-09' '2021-04-10' '2021-04-11' '2021-04-12' '2021-04-13'
 '2021-04-14' '2021-04-15' '2021-04-16' '2021-04-17' '2021-04-18'
 '2021-04-19' '2021-04-20' '2021-04-21' '2021-04-22' '2021-04-23'
 '2021-04-24' '2021-04-25' '2021-04-26' '2021-04-27' '2021-04-28'
 '2021-04-29' '2021-04-30' '2021-05-01' '2021-05-02' '2021-05-03'
 '2021-05-04' '2021-05-05' '2021-05-06' '2021-05-07' '2021-05-08'
 '2021-05-09' '2021-05-10' '2021-05-11' '2021-05-12' '2021-05-13'
 '2021-05-14' '2021-05-15' '2021-05-16' '2021-05-17' '2021-05-18'
 '2021-05-19' '2021-05-20' '2021-05-21' '2021-05-22' '2021-05-23'
 '2021-05-24' '2021-05-25' '2021-05-26' '2021-05-27' '2021-05-28'
 '2021-05-29' '2021-05-30' '2021-05-31' '2021-06-01' '2021-06-02'
 '2021-06-03' '2021-06-04' '2021-06-05' '2021-06-06' '2021-06-07'
 '2021-06-08' '2021-06-09' '2021-06-10' '2021-06-11' '2021-06-12'
 '2021-06-13' '2021-06-14' '2021-06-15' '2021-06-16' '2021-06-17'
 '2021-06-18' '2021-06-19' '2021-06-20' '2021-06-21' '2021-06-22'
 '2021-06-23' '2021-06-24' '2021-06-25' '2021-06-26' '2021-06-27'
 '2021-06-28' '2021-06-29' '2021-06-30' '2021-07-01' '2021-07-02'
 '2021-07-03' '2021-07-04' '2021-07-05' '2021-07-06' '2021-07-07'
 '2021-07-08' '2021-07-09' '2021-07-10' '2021-07-11' '2021-07-12'
 '2021-07-13' '2021-07-14' '2021-07-15' '2021-07-16' '2021-07-17'
 '2021-07-18' '2021-07-19' '2021-07-20' '2021-07-21' '2021-07-22'
 '2021-07-23' '2021-07-24' '2021-07-25' '2021-07-26' '2021-07-27'
 '2021-07-28' '2021-07-29' '2021-07-30' '2021-07-31' '2021-08-01'
 '2021-08-02' '2021-08-03' '2021-08-04' '2021-08-05' '2021-08-06'
 '2021-08-07' '2021-08-08' '2021-08-09' '2021-08-10' '2021-08-11'
 '2021-08-12' '2021-08-13' '2021-08-14' '2021-08-15' '2021-08-16'
 '2021-08-17' '2021-08-18' '2021-08-19' '2021-08-20' '2021-08-21'
 '2021-08-22' '2021-08-23' '2021-08-24' '2021-08-25' '2021-08-26'
 '2021-08-27' '2021-08-28' '2021-08-29' '2021-08-30' '2021-08-31'
 '2021-09-01' '2021-09-02' '2021-09-03' '2021-09-04' '2021-09-05'
 '2021-09-06' '2021-09-07' '2021-09-08' '2021-09-09' '2021-09-10'
 '2021-09-11' '2021-09-12' '2021-09-13' '2021-09-14' '2021-09-15'
 '2021-09-16' '2021-09-17' '2021-09-18' '2021-09-19' '2021-09-20'
 '2021-09-21' '2021-09-22' '2021-09-23' '2021-09-24' '2021-09-25'
 '2021-09-26' '2021-09-27' '2021-09-28' '2021-09-29' '2021-09-30'
 '2021-10-01' '2021-10-02' '2021-10-03' '2021-10-04' '2021-10-05'
 '2021-10-06' '2021-10-07' '2021-10-08' '2021-10-09' '2021-10-10'
 '2021-10-11' '2021-10-12' '2021-10-13' '2021-10-14' '2021-10-15'
 '2021-10-16' '2021-10-17' '2021-10-18' '2021-10-19' '2021-10-20'
 '2021-10-21' '2021-10-22' '2021-10-23' '2021-10-24' '2021-10-25'
 '2021-10-26' '2021-10-27' '2021-10-28' '2021-10-29' '2021-10-30'
 '2021-10-31' '2021-11-01' '2021-11-02' '2021-11-03' '2021-11-04'
 '2021-11-05' '2021-11-06' '2021-11-07' '2021-11-08' '2021-11-09'
 '2021-11-10' '2021-11-11' '2021-11-12' '2021-11-13' '2021-11-14'
 '2021-11-15' '2021-11-16' '2021-11-17' '2021-11-18' '2021-11-19'
 '2021-11-20' '2021-11-21' '2021-11-22' '2021-11-23' '2021-11-24'
 '2021-11-25' '2021-11-26' '2021-11-27' '2021-11-28' '2021-11-29'
 '2021-11-30' '2021-12-01' '2021-12-02' '2021-12-03' '2021-12-04'
 '2021-12-05' '2021-12-06' '2021-12-07' '2021-12-08' '2021-12-09'
 '2021-12-10' '2021-12-11' '2021-12-12' '2021-12-13' '2021-12-14'
 '2021-12-15' '2021-12-16' '2021-12-17' '2021-12-18' '2021-12-19'
 '2021-12-20' '2021-12-21' '2021-12-22' '2021-12-23' '2021-12-24'
 '2021-12-25' '2021-12-26' '2021-12-27' '2021-12-28' '2021-12-29'
 '2021-12-30' '2021-12-31' '2022-01-01' '2022-01-02' '2022-01-03'
 '2022-01-04' '2022-01-05' '2022-01-06' '2022-01-07' '2022-01-08'
 '2022-01-09' '2020-02-13' '2020-02-14' '2020-02-15' '2020-02-16'
 '2020-02-17' '2020-02-18' '2020-02-19' '2020-02-20' '2020-02-21'
 '2020-02-22' '2020-02-23' '2020-01-01' '2020-01-02' '2020-01-03'
 '2020-01-04' '2020-01-05' '2020-01-06' '2020-01-07' '2020-01-08'
 '2020-01-09' '2020-01-10' '2020-01-11' '2020-01-12' '2020-01-13'
 '2020-01-14' '2020-01-15' '2020-01-16' '2020-01-17' '2020-01-18'
 '2020-01-19' '2020-01-20' '2020-01-21' '2020-01-22' '2020-01-23'
 '2020-01-24' '2020-01-25' '2020-01-26' '2020-01-27' '2020-01-28'
 '2020-01-29' '2020-01-30' '2020-01-31' '2020-02-01' '2020-02-02'
 '2020-02-03' '2020-02-04' '2020-02-05' '2020-02-06' '2020-02-07'
 '2020-02-08' '2020-02-09' '2020-02-10' '2020-02-11' '2020-02-12']
population[3.98354280e+07 1.37348647e+09 2.87293400e+06 4.46166260e+07
 7.73540000e+04 3.39336110e+07 1.51250000e+04 9.87280000e+04
 4.56058230e+07 2.96812800e+06 1.07195000e+05 4.67844499e+09
 2.57882170e+07 9.04307200e+06 1.02233440e+07 3.96914000e+05
 1.74829500e+06 1.66303494e+08 2.87708000e+05 9.44286700e+06
 1.16323340e+07 4.04915000e+05 1.24510310e+07 6.20920000e+04
 7.79900000e+05 1.18329360e+07 2.64450000e+04 3.26345900e+06
 2.39724000e+06 2.13993441e+08 3.04230000e+04 4.41532000e+05
 6.89665500e+06 2.14970970e+07 1.22554290e+07 1.69464460e+07
 2.72242620e+07 3.80679130e+07 5.61901000e+05 6.64980000e+04
 4.91998700e+06 1.69149850e+07 1.92123620e+07 1.44421610e+09
 5.12658410e+07 8.88456000e+05 5.65701700e+06 1.75720000e+04
 5.13905300e+06 2.70536290e+07 4.08165700e+06 1.13174980e+07
 1.64796000e+05 8.96005000e+05 1.07245530e+07 9.23779860e+07
 5.81330200e+06 1.00219700e+06 7.21720000e+04 1.09537140e+07
 1.78884740e+07 1.04258327e+08 6.51850000e+06 1.44989100e+06
 3.60146200e+06 1.32518800e+06 1.17236900e+06 1.17876226e+08
 7.48962983e+08 4.47189915e+08 4.90530000e+04 3.52800000e+03
 9.02899000e+05 5.54836100e+06 6.74220000e+07 2.82534000e+05
 2.27882900e+06 2.48693700e+06 3.97977300e+06 8.39004710e+07
 3.17321280e+07 3.36910000e+04 1.03707470e+07 5.68680000e+04
 1.13015000e+05 1.82498680e+07 6.33850000e+04 1.34972370e+07
 2.01549000e+06 7.90329000e+05 1.15416830e+07 1.21493023e+09
 1.00629940e+07 7.55280000e+06 9.63416200e+06 3.68792000e+05
 1.39340903e+09 2.76361788e+08            nan 8.50287600e+07
 4.11793510e+07 4.98290400e+06 8.54100000e+04 9.29100000e+06
 6.03674710e+07 2.97346200e+06 1.26050796e+08 1.01073000e+05
 1.02690220e+07 1.89949580e+07 5.49857020e+07 1.21388000e+05
 1.78211500e+06 4.32855300e+06 6.62834700e+06 7.37935800e+06
 1.86693400e+06 6.76915100e+06 2.15906700e+06 5.18020800e+06
 6.95853800e+06 3.82540000e+04 2.68986200e+06 6.65149040e+08
 3.33065255e+09 6.34814000e+05 6.58391000e+05 2.84273330e+07
 1.96476810e+07 3.27761950e+07 5.43620000e+05 2.08557240e+07
 5.16100000e+05 5.96180000e+04 4.77511000e+06 1.27342800e+06
 1.30262220e+08 1.16255000e+05 4.02402500e+06 3.95200000e+04
 3.32928200e+06 6.28051000e+05 4.98100000e+03 3.73447870e+07
 3.21630450e+07 5.48060140e+07 2.58734400e+06 1.08730000e+04
 2.96749200e+07 1.71730940e+07 2.88217000e+05 5.12260000e+06
 6.70237900e+06 2.51308100e+07 2.11400704e+08 1.61400000e+03
 5.96581283e+08 2.08266100e+06 5.46562900e+06 4.32199540e+07
 5.22337600e+06 2.25199929e+08 1.81740000e+04 5.22275600e+06
 4.38158300e+06 9.11900500e+06 7.21964100e+06 3.33594150e+07
 1.11046910e+08 4.70000000e+01 3.77970000e+07 1.01679230e+07
 2.93052400e+06 1.91277720e+07 1.45912022e+08 1.32765170e+07
 6.09500000e+03 5.35460000e+04 1.84401000e+05 5.77100000e+03
 1.11269000e+05 2.00144000e+05 3.40100000e+04 2.23364000e+05
 3.53406800e+07 1.71963080e+07 6.87154700e+06 9.89100000e+04
 8.14134300e+06 5.45360000e+06 4.34210000e+04 5.46072600e+06
 2.07872300e+06 7.03995000e+05 1.63595000e+07 6.00419960e+07
 4.34260137e+08 5.13051840e+07 1.13813770e+07 4.67452110e+07
 2.14973060e+07 4.49093510e+07 5.91798000e+05 1.01601590e+07
 8.71549400e+06 1.82757040e+07 2.38550080e+07 9.74962500e+06
 6.14984380e+07 6.99508440e+07 1.34387500e+06 8.47824200e+06
 1.36800000e+03 1.06759000e+05 1.40337400e+06 1.19357640e+07
 8.50427360e+07 6.11793300e+06 3.92260000e+04 1.19250000e+04
 4.71235330e+07 4.34668220e+07 9.99108300e+06 6.82071140e+07
 3.32915074e+08 2.51367279e+09 3.48515200e+06 3.39357650e+07
 3.14464000e+05 8.12000000e+02 2.87049470e+07 9.81688290e+07
 1.10940000e+04 7.87496573e+09 3.04906390e+07 1.89206570e+07
 1.50921710e+07]
total_cases[5.00000e+00 8.00000e+00 1.10000e+01 ... 2.20178e+05 2.21282e+05
 2.21918e+05]
new_cases[5.000e+00 0.000e+00 3.000e+00 ... 4.872e+03 3.406e+03 4.180e+03]
new_cases_smoothed[         nan 7.140000e-01 0.000000e+00 ... 1.481429e+03 1.503143e+03
 1.519714e+03]
total_deaths[      nan 1.000e+00 2.000e+00 ... 4.735e+03 4.819e+03 4.940e+03]
new_deaths[      nan 1.000e+00 0.000e+00 ... 6.663e+03 7.231e+03 4.985e+03]
new_deaths_smoothed[         nan 1.430000e-01 2.860000e-01 ... 6.055429e+03 6.182143e+03
 6.298857e+03]
total_cases_per_million[1.2600000e-01 2.0100000e-01 2.7600000e-01 ... 1.4588889e+04 1.4662039e+04
 1.4704180e+04]
new_cases_per_million[1.2600e-01 0.0000e+00 7.5000e-02 ... 9.1372e+01 7.4277e+01 4.2141e+01]
new_cases_smoothed_per_million[       nan 1.8000e-02 0.0000e+00 ... 9.5887e+01 7.9985e+01 7.5952e+01]
total_deaths_per_million[        nan 2.50000e-02 5.00000e-02 ... 3.38454e+02 3.40309e+02
 3.41104e+02]
new_deaths_per_million[  nan 0.025 0.    ... 1.855 6.758 4.572]
new_deaths_smoothed_per_million[      nan 4.000e-03 7.000e-03 ... 3.247e+00 3.682e+00 5.045e+00]
reproduction_rate[  nan  1.5   1.51  1.49  1.48  1.47  1.52  1.53  1.54  1.55  1.56  1.57
  1.58  1.59  1.61  1.46  1.44  1.42  1.41  1.39  1.38  1.36  1.35  1.33
  1.31  1.29  1.27  1.26  1.24  1.22  1.21  1.19  1.18  1.16  1.14  1.13
  1.11  1.09  1.08  1.06  1.05  1.03  1.02  1.01  0.99  0.98  0.96  0.95
  0.93  0.92  0.9   0.89  0.88  0.87  0.85  0.84  0.83  0.82  0.81  0.8
  0.79  0.78  0.77  0.76  0.86  0.91  0.94  0.97  1.    1.04  1.1   1.15
  1.2   1.17  1.12  1.07  1.23  1.25  1.28  1.3   1.32  1.34  1.37  0.75
  0.74  0.73  0.72  0.71  0.7   0.69  0.68  0.67  0.66  0.65  0.64  1.4
  1.43  1.6   0.62  0.61  0.6   0.59  0.57  0.58  0.55  0.56  0.54  1.66
  1.7   1.74  1.75  1.68  1.63  1.65  1.71  1.78  1.87  1.96  2.02  2.03
  1.99  1.94  1.9   1.85  1.79  1.69  1.64  1.62  1.93  1.76  2.05  1.98
  1.84  1.45  0.63  0.52  0.51  0.5   0.49  0.48  0.47  0.45  0.44  0.46

total_vaccinations_per_hundred[      nan 0.000e+00 2.000e-02 ... 4.529e+01 4.763e+01 4.826e+01]
people_vaccinated_per_hundred[      nan 0.000e+00 2.000e-02 ... 2.202e+01 2.374e+01 2.420e+01]
people_fully_vaccinated_per_hundred[  nan  0.14  0.19 ... 16.04 16.88 17.84]
total_boosters_per_hundred[ nan 0.   0.01 ... 6.93 9.87 9.92]
new_vaccinations_smoothed_per_million[   nan    34.    40. ... 14062.  3836.  3870.]
new_people_vaccinated_smoothed[  nan 1367. 1580. ... 4265. 5229. 4992.]
new_people_vaccinated_smoothed_per_hundred[  nan 0.003 0.004 ... 1.276 0.986 0.995]
stringency_index[  8.33  27.78  38.89  41.67  50.93  59.26  67.59  78.7   84.26  75.
  71.3   60.19  48.15  21.3   28.7   25.    16.67   9.26  12.04  30.56
  26.85  54.63  37.96  43.52  46.3   56.02  52.31  22.22  18.52    nan
  42.59  35.19  36.11  51.85  81.48  89.81  83.33  86.11  68.52  62.96
  57.41  65.74  56.48  63.89  45.37   0.     5.56  86.57  92.13  76.85
  87.96  74.07  79.63  85.19  75.93  72.22  69.44  77.78  70.83  61.57
  50.46  49.07  52.78  39.81  50.    20.37  31.48  53.7   55.56  40.74
  11.11  33.33  90.74  76.39  79.17  81.02  58.8   61.11  58.33  56.94
  62.5   55.09  66.67  88.89 100.    98.15  94.44  92.59  82.87  80.09
  81.94  77.31  71.76  70.37  44.44  47.22  68.06  59.72  54.17  37.04
  32.41  25.93  23.15  33.8   26.39  19.91  13.89  19.44  73.15  64.35
  67.13  65.28  63.43  62.04  68.98  75.46  60.65  78.24  53.24  44.91
  46.76  39.35  48.61  36.57  42.13  47.69  74.54  72.69  40.28  45.83
  34.26  64.81  82.41  91.67  96.3   93.52  66.2   69.91  73.61  51.39
  49.54  29.63  87.04  43.06  97.22  89.35  87.5   83.8   31.02  30.09
  18.06  29.17  34.72  80.56  57.87  41.2   14.81  24.07  27.31  15.74
   2.78  12.96  84.72  38.43  37.5   35.65  31.94  17.59   6.48  43.98
  32.87  10.19  85.65  88.43  95.37  20.83  25.46  18.98  21.76]
population_density[5.4422000e+01           nan 1.0487100e+02 1.7348000e+01 1.6375500e+02
 2.3890000e+01 2.3184500e+02 1.6177000e+01 1.0293100e+02 5.8480000e+02
 3.2020000e+00 1.0674900e+02 1.1930900e+02 3.9497000e+01 1.9359070e+03
 1.2650360e+03 6.6446300e+02 4.6858000e+01 3.7556400e+02 1.6426000e+01
 9.9110000e+01 1.3088200e+03 2.1188000e+01 1.0202000e+01 6.8496000e+01
 4.0440000e+00 2.5040000e+01 2.0797300e+02 8.1347000e+01 6.5180000e+01
 7.0151000e+01 4.2306200e+02 9.0672000e+01 5.0885000e+01 4.0370000e+00
 1.3558000e+02 2.5649600e+02 7.4790000e+00 1.1833000e+01 2.4282000e+01
 1.4767400e+02 4.4223000e+01 4.3735200e+02 1.5405000e+01 9.6079000e+01
 7.6399000e+01 7.3726000e+01 1.1040800e+02 3.6264400e+02 1.2765700e+02
 1.3717600e+02 3.5879000e+01 1.3652000e+02 4.1285000e+01 9.8567000e+01
 2.2287300e+02 6.6939000e+01 9.7999000e+01 3.0781100e+02 4.5194000e+01
 4.4304000e+01 3.1033000e+01 7.9492000e+01 1.0495700e+02 3.5308000e+01
 4.9562000e+01 1.8136000e+01 1.2257800e+02 7.7324000e+01 7.8590000e+00
 2.0756600e+02 6.5032000e+01 2.3701600e+02 1.2671900e+02 3.4571000e+03
 8.3479000e+01 1.3700000e-01 3.1713200e+02 1.5783400e+02 5.1755000e+01
 6.6191000e+01 3.9520000e+00 3.9844800e+02 8.2805000e+01 7.0397140e+03
 1.0804300e+02 3.4040000e+00 4.5041900e+02 1.4572500e+02 4.9831000e+01
 8.8125000e+01 6.9874000e+01 1.4787200e+02 4.0260600e+02 2.0585900e+02
 2.6687900e+02 3.4777800e+02 1.0928500e+02 6.6810000e+00 8.7324000e+01
 1.4370100e+02 1.6815500e+02 2.3212800e+02 3.2333000e+01 2.9715000e+01
 3.1212000e+01 5.9456100e+02 7.3562000e+01 4.9127000e+01 3.6230000e+00
 2.3701200e+02 4.5135000e+01 2.3144700e+02 2.0546766e+04 4.3951000e+01
 1.9751900e+02 9.6254000e+01 1.4544330e+03 1.5196000e+01 1.4540370e+03
 2.9515000e+02 4.2890000e+00 6.2296200e+02 6.6444000e+01 1.5077700e+02
 1.2365500e+02 1.9347500e+04 1.9800000e+00 4.6280000e+01 8.0080000e+01
 3.7728000e+01 8.1721000e+01 3.0780000e+00 6.8245000e+02 2.0443000e+02
 5.0854400e+02 1.5342000e+01 1.8206000e+01 5.1667000e+01 1.6955000e+01
 2.0958800e+02 8.2600000e+01 1.4462000e+01 1.4980000e+01 2.5557300e+02
 4.7237000e+01 7.7820200e+02 5.5133000e+01 1.8220000e+01 1.7144000e+01
 2.5129000e+01 3.5187300e+02 1.2402700e+02 1.1237100e+02 2.2732200e+02
 8.5129000e+01 8.8230000e+00 4.9486900e+02 2.1286500e+02 2.9318700e+02
 2.8178700e+02 6.9413000e+01 5.5666700e+02 2.1284100e+02 1.5322000e+01
 8.2328000e+01 8.0291000e+01 2.0835400e+02 1.0470000e+02 7.9157310e+03
 1.2090880e+03 1.1312800e+02 1.0261900e+02 2.1841000e+01 2.3500000e+01
 4.6754000e+01 5.2796700e+02 9.3105000e+01 3.4195500e+02 2.3258000e+01
 3.6120000e+00 2.4718000e+01 2.1424300e+02 6.4281000e+01 6.4699000e+01
 1.3513200e+02 8.7176000e+01 1.4336600e+02 1.5002800e+02 2.6688600e+02
 7.4228000e+01 1.0491400e+02 1.2253000e+01 3.7312000e+01 3.7306700e+02
 2.1375900e+02 7.7390000e+01 1.1244200e+02 2.7289800e+02 3.5608000e+01
 1.9751000e+01 7.6134000e+01 2.2662000e+01 3.6253000e+01 3.0812700e+02
 5.8045000e+01 5.3508000e+01 2.2995000e+01 4.2729000e+01]
median_age[18.6  nan 38.  29.1 16.8 32.1 31.9 35.7 41.2 37.9 44.4 32.4 34.3 27.5
 39.8 40.3 41.8 25.  18.8 28.6 25.4 42.5 25.8 33.5 44.7 17.6 17.5 25.6
 41.4 25.7 18.3 16.7 35.4 38.7 32.2 20.4 19.  33.6 18.7 44.  43.1 41.7
 37.3 43.3 17.  42.3 27.6 28.1 25.3 22.4 19.3 42.7 21.5 19.8 42.8 42.
 32.7 23.1 46.6 21.1 45.3 29.4 22.9 19.4 26.3 24.3 24.9 44.8 43.4 28.2
 29.3 20.  30.6 47.9 31.4 48.2 23.2 33.7 24.4 43.9 31.1 22.2 19.2 29.
 43.5 39.7 39.2 19.6 18.1 29.9 16.4 42.4 20.3 37.4 23.  37.6 39.1 29.6
 17.7 22.  43.2 33.4 27.3 15.1 30.7 23.5 29.7 22.6 26.5 25.2 46.2 43.
 39.6 34.9 31.8 36.2 19.1 44.5 20.8 45.5 34.1 19.7 41.  21.7 42.2 23.3
 40.1 18.  22.3 31.6 26.9 34.  40.8 38.3 35.6 32.6 30.9]
aged_65_older[ 2.581    nan 13.188  6.211  2.405  6.933 11.198 11.232 13.085 15.504
 19.202  6.018  8.996  2.372  5.098 14.952 14.799 18.571  3.853  3.244
  4.885  6.704 16.569  3.941  8.552  4.591 20.801  2.409  2.562  4.412
  3.165 16.984  4.46   3.655  2.486 11.087 10.641  7.646  2.963  3.402
  9.468  2.933 19.724 14.738 16.367 13.416 19.027  3.02  19.677  4.213
  6.981  7.104  5.159  8.273  2.846  3.607 19.452  3.163  3.526  6.224
 21.228 19.718  7.775  4.45   2.339 14.864 21.453  3.385 20.396  7.304
  4.694  3.135  3.002  5.305  4.8    4.652 16.303 18.577 14.431  5.989
  5.319  5.44   3.186 13.928 11.733 23.021  9.684 27.049  3.81   6.991
  2.686  3.895  2.345  4.489  4.029 19.754  8.514  4.506  3.057  4.424
 19.002 14.312  9.798  2.929  2.979  6.293  4.12   2.519 19.426  3.138
 10.945  6.857  4.81  10.864  4.031 14.762  6.769  3.158  5.732  3.552
  5.809 18.779  9.954 15.322  5.445  2.553  2.751 13.26  16.821  2.355
  4.495  3.043  7.918  3.808  6.378  7.151  4.803 16.763 21.502  1.307
 17.85  14.178  2.974  9.721  7.724  5.606  2.886  3.295  3.008 17.366
  8.606  2.538 12.922 15.07  19.062  3.507  2.731  5.344 13.914  3.441
 19.436 10.069  3.548 19.985 18.436  3.466  3.108 11.373  3.556  2.839
  5.82  10.014  8.001  8.153  4.277  2.168 16.462  1.144 18.517 15.413
 14.655  4.469  4.394  6.614  7.15   8.696  2.922  2.48   2.822]
aged_70_older[ 1.337    nan  8.643  3.857  1.362  4.631  7.441  7.571  7.452 10.129
 13.748  3.871  5.2    1.387  3.262  9.473  9.788 12.849  2.279  1.942
  2.977  4.393 10.711  2.242  5.06   2.382 13.272  1.358  1.504  2.385
  1.919 10.797  3.437  2.251  1.446  6.938  5.929  4.312  1.726  2.063
  5.694  1.582 13.053  9.719 10.068  8.563 11.58   1.745 12.325  2.38
  4.419  4.458  2.891  5.417  1.752  2.171 13.491  1.845  3.284 13.264
 13.079  4.593  2.976  1.417 10.244 15.957  1.948 14.524  5.021  3.016
  1.733  1.565  2.837  2.954  2.883 10.158 11.976  9.207  3.414  3.053
  3.182  1.957  8.678  7.359 16.24   6.39  18.493  2.361  4.625  1.528
  2.21   1.114  2.882  2.322 14.136  5.43   2.647  1.756  2.816 13.778
  9.842  4.991  1.686  1.783  3.407  2.875  1.486 11.324  1.792  5.884
  4.321  2.392  6.955  2.421  9.395  4.209  1.87   3.12   2.085  3.212
 11.881  6.489  9.72   3.519  1.378  1.447  8.16  10.813  1.53   2.78
  5.03   2.142  3.833  4.455  2.661 10.202 14.924  0.617 11.69   9.393
  1.642  6.405  4.832  3.564  2.162  1.796  5.586  1.285  7.049  9.167
 12.93   2.043  1.496  8.622  2.032 13.799  5.331  2.034  4.229 13.433
 12.644  2.577  8.353  2.155  1.874  6.89   1.897  1.525  4.032  5.819
  5.075  5.061  2.541  1.308 11.133  0.526 12.527  9.732 10.361  2.873
  2.62   3.915  4.718  5.355  1.583  1.542  1.882]
gdp_per_capita[  1803.987        nan  11803.431  13913.839   5819.495  21490.943
  18933.907   8787.58   35973.781  44648.71   45436.686  15847.419
  27717.847  43290.705   3523.984  16978.068  17167.967  42658.576
   7824.362   2064.236  50669.315   8708.597   6885.829  11713.895
  15807.374  14103.452  71809.251  18563.307   1703.102    702.225
   3645.07    3364.926  44017.591   6222.554  49903.029    661.24
   1768.153  22767.037  15308.712  13254.949   1413.89    4881.406
  15524.995   3601.006  22669.797  32415.132  32605.906    808.133
  46682.515   2705.406   9673.367  14600.861  10581.936  10550.206
   7292.458  22604.873   1510.459  29481.252   7738.975   1729.927
   8702.975  40585.721  38605.671  16562.413   1561.767   9745.079
  45229.245   4227.63   24574.382  13593.877   7423.808   1998.926
   1548.675   7435.047   1653.173   4541.795  56054.92   26777.561
  46482.958   6426.674  11188.744  19082.62   15663.986  67335.293
  33132.32   35220.084   8193.571  39002.223   8337.49   24055.588
   2993.028   1981.132   9795.834  65530.537   3393.474   6397.36
  25063.846  13367.565   2851.153    752.788  17881.509  29524.265
  94277.965 104861.851   1416.44    1095.042  26808.164  15183.616
   2014.306  36513.323   3819.202   3597.633  20292.745  17336.469
   3299.464   5189.972  11840.846  16409.288   7485.013   1136.103
   5591.597   9541.808  12895.635   2442.804  48472.545  36085.843
   5321.444    926.      5338.454  13111.214  64800.057  37960.709
   5034.708  13240.405   4449.898  22267.037   3823.194   8827.01
  12236.706   7599.188  27216.445  27936.896 116935.6    23313.199
  24765.954   1854.211  24654.385  12951.839  10727.146   6021.557
  56861.47    3052.714  49045.411   2470.58   14048.881  26382.287
   1390.3    85535.383  36327.232  30155.152  31400.84    2205.923
  12294.876  35938.374   1569.888  34272.36   11669.077   4466.507
  13767.119  46949.283  57410.166   2896.913   2683.304  16277.671
   6570.102   1429.813   5425.621  28763.071  10849.297  25129.341
  16389.023   3575.104   1697.707   7894.393  67293.483  39753.244
  54225.446  20551.409   6253.104   2921.909  16745.022   6171.884
  15469.207   1479.147   3689.251   1899.775]
extreme_poverty[ nan  1.1  0.5  0.6  1.8  0.7 14.8  0.2 49.6  1.5  7.1  3.4 43.7 71.7
 23.8 38.4  1.3  4.5 18.1 37.  28.2 77.1 22.5  1.6  3.6  2.2 26.7  1.4
 10.1  4.2 12.   8.7 35.3 67.1 23.5 16.  21.2  5.7  2.5  2.   0.1 36.8
 22.7 59.6 38.6 77.6 71.4  6.   1.  62.9  6.4 13.4 15.   3.2 44.5  5.
  4.   1.7  3.5 56.  32.3 38.  52.2 25.1 18.9  4.8 49.1 30.3 49.2  3.3
 41.6  1.2 13.2 10.  18.8 57.5 21.4]
cardiovasc_death_rate[597.029     nan 304.195 278.364 109.135 276.045 191.511 191.032 341.01
 107.791 145.183 559.812 235.954 151.689 298.003 170.05  443.129 114.898
 176.957 235.848 139.547 217.066 204.299 329.635 237.372 177.961 201.285
 424.688 269.048 293.068 270.892 244.661 105.599 182.219 435.727 280.995
 127.993 261.899 124.24  261.516 344.094 137.973 303.74  253.782 190.968
 141.171 227.485 318.949 114.767 258.037 227.376 266.653 140.448 525.432
 167.295 202.812 311.11  255.569 333.436 182.634 412.82  153.507  86.06
 259.967 331.43  496.218 156.139 298.245 175.695 199.941 243.964 155.898
 336.717 382.474 373.159 430.548 240.208 278.296 117.992 282.28  342.864
 270.308 218.612 126.459  93.32  113.151 206.537  79.37  208.257 466.792
 218.637 434.657 132.235 436.362 368.111 350.06  266.591 405.126 272.509
 341.862 342.989 128.275 405.994 227.349 260.942 164.905 268.024 168.711
 557.793 232.347 224.644 152.783 454.343 408.502 460.043 387.305 419.146
 329.942 202.104 243.811 260.797 109.361 128.797 137.016 238.339 181.013
 322.688 114.316 266.342 423.031 265.91  128.346 561.494 199.128  85.755
 370.437 227.331 127.842 176.69  370.946 431.297 191.375 204.62  252.675
 348.977 270.113 259.538 241.219 439.415 242.648 325.721  92.243 287.959
 153.493 459.78  365.769 200.38   85.998 280.775  99.403 197.093 431.388
 258.314 133.982  99.739 376.264 103.957 427.698 217.288 109.861 335.346
 280.033 227.49  228.467 318.991 171.285 536.783 213.333 539.849 317.84
 122.137 151.089 160.708 724.417 546.3   204.85  245.465 233.07  495.003
 234.499 307.846]
diabetes_prevalence[ 9.59   nan 10.08  6.73  7.97  3.94 13.17  5.5   7.11 11.62  5.07  6.35
 16.52  8.38 13.57  5.18  4.29 17.11  0.99 13.    9.75  6.89  4.81  8.11
 13.67 12.79  5.81  2.42  6.05  4.    7.2   7.37 13.22  6.1   8.46  9.74
  7.44 11.88  8.78  5.59  8.27  9.24  6.82  6.41  8.2   5.55 17.31  8.87
  7.78  4.02  7.47 14.49  5.76  4.77 22.63  1.91  8.31  4.97  4.55  2.16
 10.71 10.18  6.65  7.21  8.33  7.55  5.31 10.39  6.32  8.83  3.28  6.74
  4.78 11.28  5.72 11.75  2.92 22.66 15.84  4.91 12.71 10.43  7.77  3.67
  4.42 16.74  9.19 30.53 22.02 13.06 12.02  5.46  4.82  7.14  3.3   4.61
 24.07  7.26  5.29 23.36  8.08 11.47 12.61  8.35 15.89 10.59 17.65  5.95
  7.07  5.91  9.85  6.18  4.28 12.84  9.21  5.64 17.72 10.55 10.99  7.29
  7.25 18.68  5.52  6.8   7.17 10.68 15.67 12.54  4.79  5.75  7.04  6.86
  6.15 15.42 10.97  8.52 12.13 27.25  2.5  17.26 10.79  6.93  7.57  6.47
  6.    8.51  5.35  1.82]
female_smokers[   nan  7.1    0.7   29.    16.2    1.5   13.    28.4    0.3    3.1
  5.8    1.     1.9   10.5   25.1    0.6   30.2    5.7   10.1    2.
 30.1    1.6   12.     2.1   34.2    4.7    4.4    1.7    6.4   34.3
 17.1   19.6   30.5   19.3    8.5    0.2    2.5   24.5    0.4   10.2
 18.3    5.3   28.2   35.3    2.9   26.8   14.3    2.8    0.8   23.
 15.4   19.8   11.2    7.     1.2   35.9    2.7    3.6    7.3   25.6
 26.9   21.3   20.9    3.2    6.9    5.9    5.5   44.     5.1    6.3
  9.7   43.     9.5   24.4   14.8    0.1    0.5    7.7    2.4   23.5
  5.     4.8    7.8   23.3   16.3   22.9   23.4   16.7    1.8   37.7
  8.8    5.2   23.1   20.1    8.1    6.2   27.4    7.4   18.8   22.6
  3.3    0.9   11.8    1.1   14.1    3.4   13.5   20.    19.1   14.
  1.3    6.434  7.6  ]
male_smokers[   nan 51.2   30.4   37.8   27.7   52.1   16.5   30.9   42.5   20.4
 37.6   44.7   14.5   46.1   31.4   12.3   47.7   34.4   17.9   44.4
 23.9   33.7   16.6   41.5   48.4   13.5   23.6   52.3   17.4   39.9
 53.3   52.7   38.3   18.8   24.5   19.1   50.1   11.4   39.3    8.5
 34.8   22.6   35.6   31.2   55.5   33.1    7.7   52.    23.1   15.2
 20.6   76.1   21.1   25.7   35.4   27.8   28.6   43.1   58.9   37.
 50.5   51.    40.7   53.9   18.1   38.    26.    24.7   42.4   55.
 23.    30.2   21.4   44.6   46.5   47.9   47.1   29.1   35.2   34.2
 36.9   27.3   17.2   15.4   10.8   20.7   15.6   36.7   22.7    9.9
 48.8   21.6   40.8   30.    26.9   37.1   58.3   21.    38.1   25.4
 40.2   35.7   41.3   28.3   37.7   25.    33.2   40.9   27.    42.9
 18.9   28.9   26.7   38.8   78.1   14.2   65.8   41.1   16.7   47.4
 37.4   24.6   19.9   34.5   45.9   34.635 29.2   30.7  ]
handwashing_facilities[ 37.746     nan  83.741  26.664  94.043  83.241  34.808  88.469  90.083
  11.035  79.807  25.383  97.164  11.877   6.144  66.229   2.735  16.603
   5.818  65.386  15.574  47.964  83.841  19.351  85.198   4.472  55.182
  80.635  89.827  90.65   24.64   24.097   7.96    7.876  41.047  76.665
  17.45    6.403  77.159  22.863  84.169  59.55   64.204  94.576  66.425
  98.999  24.651  89.22   49.839   2.117   1.188  50.54    8.704  95.803
  52.232  82.502  15.95   87.847  86.979  71.18   12.227  79.287  44.6
  47.782   8.978  41.949  97.4    59.607  79.602  78.463   4.617  87.202
  41.34   20.859  97.719  19.275  35.89    9.831  43.993  23.437  67.779
  70.598  72.704  47.953  90.67   28.178  10.475  89.443  78.687 100.
  21.222  25.209  85.847  60.13   49.542  13.938  36.791]
hospital_beds_per_thousand[ 0.5      nan  2.89   1.9    3.8    5.     4.2    3.84   7.37   4.7
  2.9    2.     0.8    5.8   11.     5.64   1.3    1.7    1.1    3.5
  1.8    2.2    2.7    7.454  0.4    2.5    2.1    1.     2.11   4.34
  1.71   1.13   5.54   5.2    3.4    6.63   1.4    1.6    1.5    0.7
  4.69   0.3    2.3    3.28   5.98   6.3    2.6    8.     0.9    4.21
  3.7    0.6    7.02   2.91   0.53   1.04   2.96   2.99   3.18  13.05
  6.7    4.5    5.57   2.397  6.56   4.51   0.2    0.1    4.485  1.38
 13.8    7.     3.861  3.32   2.61   4.28   3.6    4.8    6.62   3.39
  1.2    6.892  8.05   5.609  2.4    5.82   2.32  12.27   2.97   3.1
  2.22   4.53   5.9    3.     2.81   7.4    8.8    2.54   2.77   2.8
  4.     2.705]
life_expectancy[64.83   nan 78.57 76.88 83.73 61.15 81.88 77.02 76.67 75.09 76.29 83.44
 81.54 73.   73.92 77.29 72.59 79.19 74.79 81.63 74.62 61.77 82.59 71.78
 71.51 77.79 77.4  69.59 75.88 79.07 75.86 75.05 61.58 69.82 59.29 82.43
 72.98 83.92 53.28 54.24 80.18 76.91 64.32 64.57 76.25 80.28 57.78 78.49
 78.8  78.88 80.98 79.38 60.68 80.9  67.11 75.   74.08 77.01 71.99 73.32
 58.74 66.32 78.74 60.19 66.6  80.67 81.44 67.44 81.91 82.66 77.66 66.47
 62.05 73.77 81.33 64.07 79.93 82.24 71.7  72.4  74.3  61.6  58.32 69.91
 64.   75.27 84.86 82.99 69.66 71.72 76.68 70.6  82.3  81.4  82.97 83.51
 74.47 84.63 74.53 73.6  66.7  68.37 75.49 71.45 67.92 75.29 78.93 54.33
 64.1  72.91 82.49 75.93 82.25 84.24 67.04 64.26 76.16 78.92 59.31 82.53
 73.7  64.92 74.99 67.88 71.9  86.75 69.87 74.16 60.85 67.13 63.71 59.96
 70.78 82.28 77.55 82.29 74.48 62.42 54.69 73.71 75.8  82.4  77.86 67.27
 74.05 78.51 64.5  74.25 76.74 71.23 78.73 82.05 80.23 76.05 72.58 69.02
 80.56 76.23 76.2  81.07 72.53 84.97 70.39 75.13 67.94 76.   73.4  54.7
 83.62 78.95 77.54 81.32 57.4  64.13 83.03 57.85 83.56 76.98 65.31 71.68
 82.8  83.78 72.7  80.46 71.1  65.46 77.15 69.5  61.04 81.86 70.91 73.51
 76.7  77.69 68.19 80.22 67.57 63.37 72.06 77.97 78.86 77.91 70.47 75.12
 75.4  79.94 66.12 63.89 61.49]
human_development_index[0.511   nan 0.795 0.748 0.868 0.581 0.778 0.845 0.776 0.944 0.922 0.756
 0.814 0.852 0.632 0.823 0.931 0.716 0.545 0.654 0.718 0.78  0.735 0.765
 0.838 0.816 0.452 0.433 0.594 0.563 0.929 0.665 0.397 0.398 0.851 0.761
 0.767 0.554 0.574 0.81  0.538 0.783 0.887 0.9   0.48  0.94  0.524 0.742
 0.759 0.707 0.673 0.592 0.459 0.892 0.611 0.485 0.743 0.938 0.901 0.703
 0.496 0.812 0.947 0.888 0.779 0.663 0.477 0.682 0.51  0.634 0.949 0.854
 0.645 0.674 0.955 0.919 0.734 0.729 0.825 0.601 0.63  0.806 0.697 0.613
 0.866 0.744 0.527 0.724 0.882 0.916 0.528 0.483 0.74  0.434 0.895 0.704
 0.546 0.804 0.62  0.75  0.737 0.829 0.686 0.456 0.583 0.646 0.602 0.66
 0.394 0.539 0.774 0.957 0.813 0.557 0.826 0.708 0.815 0.555 0.728 0.777
 0.88  0.864 0.848 0.828 0.824 0.543 0.738 0.715 0.625 0.512 0.796 0.86
 0.917 0.567 0.709 0.904 0.782 0.945 0.668 0.529 0.606 0.515 0.725 0.82
 0.544 0.89  0.932 0.926 0.817 0.72  0.609 0.711 0.47  0.584 0.571]
excess_mortality_cumulative_absolute[    nan  -190.8  -165.  ... 26137.6 31213.  37684. ]
excess_mortality_cumulative[  nan -4.34 -2.59 ... -5.8   9.16 13.95]
excess_mortality[  nan  2.88  1.31 ... 25.95 40.99 58.9 ]
excess_mortality_cumulative_per_million[          nan  -66.41294231  -57.4325759  ...  770.2080681   919.7670953
 1110.450877  ]

# Creating dataframe for covid by country table

In [97]:
# removing iso_codes OWID to create dataframe for countries (dropping continents)
covid_countries_df = covid_dataset_df[covid_dataset_df['iso_code'].str.contains(r'[OWID.]')!=True]

In [98]:
covid_countries_df['iso_code'].unique()

array(['AFG', 'ALB', 'ATG', 'ARG', 'ARM', 'AUS', 'AUT', 'AZE', 'BHS',
       'BHR', 'BRB', 'BLR', 'BEL', 'BLZ', 'BEN', 'BMU', 'BTN', 'BES',
       'BRA', 'VGB', 'BRN', 'BGR', 'BFA', 'KHM', 'CMR', 'CAN', 'CPV',
       'CYM', 'CAF', 'CHL', 'CHN', 'HRV', 'CUB', 'CYP', 'CZE', 'ECU',
       'EGY', 'SLV', 'GNQ', 'EST', 'ETH', 'FLK', 'FRA', 'PYF', 'GAB',
       'GMB', 'GHA', 'GRC', 'GRL', 'GTM', 'GGY', 'GNB', 'GUY', 'HKG',
       'HUN', 'JAM', 'JPN', 'JEY', 'KAZ', 'KEN', 'KGZ', 'LVA', 'LBN',
       'LBR', 'LBY', 'LTU', 'LUX', 'MAC', 'MYS', 'MLT', 'MHL', 'MRT',
       'MUS', 'MEX', 'FSM', 'MNG', 'MNE', 'MSR', 'MAR', 'MMR', 'NAM',
       'NRU', 'NPL', 'NCL', 'NZL', 'NER', 'NGA', 'PAK', 'PSE', 'PAN',
       'PNG', 'PRY', 'PER', 'PHL', 'PCN', 'PRT', 'QAT', 'RUS', 'SHN',
       'KNA', 'LCA', 'SPM', 'VCT', 'SMR', 'STP', 'SAU', 'SEN', 'SRB',
       'SYC', 'SLE', 'SGP', 'SXM', 'SVK', 'SVN', 'SLB', 'ZAF', 'ESP',
       'LKA', 'SUR', 'CHE', 'SYR', 'TJK', 'TZA', 'THA', 'TLS', 'TKL',
       'TUN', 'TUR', 'TKM', 'TCA', 'TUV', 'UGA', 'UKR', 'ARE', 'GBR',
       'USA', 'URY', 'UZB', 'VUT', 'VAT', 'VEN', 'VNM', 'YEM', 'ZMB'],
      dtype=object)

In [99]:
covid_countries_df

,iso_code,continent,location,date,population,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-02-24,39835428.0,5.0,5.0,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-02-25,39835428.0,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-02-26,39835428.0,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-02-27,39835428.0,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-02-28,39835428.0,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152734,ZMB,Africa,Zambia,2022-01-05,18920657.0,269991.0,4512.0,3764.714,3772.0,10.0,...,3.1,24.7,13.938,2.0,63.89,0.584,NaN,NaN,NaN,NaN
152735,ZMB,Africa,Zambia,2022-01-06,18920657.0,274087.0,4096.0,3556.286,3782.0,10.0,...,3.1,24.7,13.938,2.0,63.89,0.584,NaN,NaN,NaN,NaN
152736,ZMB,Africa,Zambia,2022-01-07,18920657.0,278276.0,4189.0,3428.857,3790.0,8.0,...,3.1,24.7,13.938,2.0,63.89,0.584,NaN,NaN,NaN,NaN
152737,ZMB,Africa,Zambia,2022-01-08,18920657.0,281576.0,3300.0,3375.429,3798.0,8.0,...,3.1,24.7,13.938,2.0,63.89,0.584,NaN,NaN,NaN,NaN
152738,ZMB,Africa,Zambia,2022-01-09,18920657.0,282904.0,1328.0,3318.143,3812.0,14.0,...,3.1,24.7,13.938,2.0,63.89,0.584,NaN,NaN,NaN,NaN

In [100]:
#dropping columns

cols = [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 
        45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66]

new_df = covid_countries_df.drop(covid_countries_df.columns[cols], axis=1)

In [101]:
new_df

,iso_code,continent,location,date,population,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,...,new_deaths_smoothed_per_million,reproduction_rate,icu_patients,icu_patients_per_million,hosp_patients,hosp_patients_per_million,weekly_icu_admissions,weekly_icu_admissions_per_million,weekly_hosp_admissions,weekly_hosp_admissions_per_million
0,AFG,Asia,Afghanistan,2020-02-24,39835428.0,5.0,5.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-02-25,39835428.0,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-02-26,39835428.0,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-02-27,39835428.0,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-02-28,39835428.0,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152734,ZMB,Africa,Zambia,2022-01-05,18920657.0,269991.0,4512.0,3764.714,3772.0,10.0,...,0.347,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152735,ZMB,Africa,Zambia,2022-01-06,18920657.0,274087.0,4096.0,3556.286,3782.0,10.0,...,0.393,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152736,ZMB,Africa,Zambia,2022-01-07,18920657.0,278276.0,4189.0,3428.857,3790.0,8.0,...,0.423,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152737,ZMB,Africa,Zambia,2022-01-08,18920657.0,281576.0,3300.0,3375.429,3798.0,8.0,...,0.438,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152738,ZMB,Africa,Zambia,2022-01-09,18920657.0,282904.0,1328.0,3318.143,3812.0,14.0,...,0.521,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [102]:
new_df = new_df.rename_axis('ind_con')
new_df

,iso_code,continent,location,date,population,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,...,new_deaths_smoothed_per_million,reproduction_rate,icu_patients,icu_patients_per_million,hosp_patients,hosp_patients_per_million,weekly_icu_admissions,weekly_icu_admissions_per_million,weekly_hosp_admissions,weekly_hosp_admissions_per_million
ind_con,,,,,,,,,,,,,,,,,,,,,
0,AFG,Asia,Afghanistan,2020-02-24,39835428.0,5.0,5.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-02-25,39835428.0,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-02-26,39835428.0,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-02-27,39835428.0,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-02-28,39835428.0,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152734,ZMB,Africa,Zambia,2022-01-05,18920657.0,269991.0,4512.0,3764.714,3772.0,10.0,...,0.347,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152735,ZMB,Africa,Zambia,2022-01-06,18920657.0,274087.0,4096.0,3556.286,3782.0,10.0,...,0.393,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152736,ZMB,Africa,Zambia,2022-01-07,18920657.0,278276.0,4189.0,3428.857,3790.0,8.0,...,0.423,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152737,ZMB,Africa,Zambia,2022-01-08,18920657.0,281576.0,3300.0,3375.429,3798.0,8.0,...,0.438,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152738,ZMB,Africa,Zambia,2022-01-09,18920657.0,282904.0,1328.0,3318.143,3812.0,14.0,...,0.521,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [103]:
# saving dataframe as csv file (country table)
new_df.to_csv('Resources/covid_countries.csv', index=True)

# Creating dataframe for continent

In [104]:
covid_dataset_df

,iso_code,continent,location,date,population,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-02-24,39835428.0,5.0,5.0,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-02-25,39835428.0,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-02-26,39835428.0,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-02-27,39835428.0,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-02-28,39835428.0,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153395,ZWE,Africa,Zimbabwe,2022-01-05,15092171.0,219057.0,1379.0,1644.143,5092.0,14.0,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
153396,ZWE,Africa,Zimbabwe,2022-01-06,15092171.0,220178.0,1121.0,1207.143,5108.0,16.0,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
153397,ZWE,Africa,Zimbabwe,2022-01-07,15092171.0,221282.0,1104.0,1146.286,5136.0,28.0,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
153398,ZWE,Africa,Zimbabwe,2022-01-08,15092171.0,221918.0,636.0,1100.571,5148.0,12.0,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
153399,ZWE,Africa,Zimbabwe,2022-01-09,15092171.0,221918.0,NaN,NaN,5148.0,NaN,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN

In [105]:
covid_dataset_df['iso_code'].unique()

array(['AFG', 'OWID_AFR', 'ALB', 'DZA', 'AND', 'AGO', 'AIA', 'ATG', 'ARG',
       'ARM', 'ABW', 'OWID_ASI', 'AUS', 'AUT', 'AZE', 'BHS', 'BHR', 'BGD',
       'BRB', 'BLR', 'BEL', 'BLZ', 'BEN', 'BMU', 'BTN', 'BOL', 'BES',
       'BIH', 'BWA', 'BRA', 'VGB', 'BRN', 'BGR', 'BFA', 'BDI', 'KHM',
       'CMR', 'CAN', 'CPV', 'CYM', 'CAF', 'TCD', 'CHL', 'CHN', 'COL',
       'COM', 'COG', 'COK', 'CRI', 'CIV', 'HRV', 'CUB', 'CUW', 'CYP',
       'CZE', 'COD', 'DNK', 'DJI', 'DMA', 'DOM', 'ECU', 'EGY', 'SLV',
       'GNQ', 'ERI', 'EST', 'SWZ', 'ETH', 'OWID_EUR', 'OWID_EUN', 'FRO',
       'FLK', 'FJI', 'FIN', 'FRA', 'PYF', 'GAB', 'GMB', 'GEO', 'DEU',
       'GHA', 'GIB', 'GRC', 'GRL', 'GRD', 'GTM', 'GGY', 'GIN', 'GNB',
       'GUY', 'HTI', 'OWID_HIC', 'HND', 'HKG', 'HUN', 'ISL', 'IND', 'IDN',
       'OWID_INT', 'IRN', 'IRQ', 'IRL', 'IMN', 'ISR', 'ITA', 'JAM', 'JPN',
       'JEY', 'JOR', 'KAZ', 'KEN', 'KIR', 'OWID_KOS', 'KWT', 'KGZ', 'LAO',
       'LVA', 'LBN', 'LSO', 'LBR', 'LBY', 'LIE', 'LTU', 'OWID_LIC',
       'OWID_LMC', 'LUX', 'MAC', 'MDG', 'MWI', 'MYS', 'MDV', 'MLI', 'MLT',
       'MHL', 'MRT', 'MUS', 'MEX', 'FSM', 'MDA', 'MCO', 'MNG', 'MNE',
       'MSR', 'MAR', 'MOZ', 'MMR', 'NAM', 'NRU', 'NPL', 'NLD', 'NCL',
       'NZL', 'NIC', 'NER', 'NGA', 'NIU', 'OWID_NAM', 'MKD', 'OWID_CYN',
       'NOR', 'OWID_OCE', 'OMN', 'PAK', 'PLW', 'PSE', 'PAN', 'PNG', 'PRY',
       'PER', 'PHL', 'PCN', 'POL', 'PRT', 'QAT', 'ROU', 'RUS', 'RWA',
       'SHN', 'KNA', 'LCA', 'SPM', 'VCT', 'WSM', 'SMR', 'STP', 'SAU',
       'SEN', 'SRB', 'SYC', 'SLE', 'SGP', 'SXM', 'SVK', 'SVN', 'SLB',
       'SOM', 'ZAF', 'OWID_SAM', 'KOR', 'SSD', 'ESP', 'LKA', 'SDN', 'SUR',
       'SWE', 'CHE', 'SYR', 'TWN', 'TJK', 'TZA', 'THA', 'TLS', 'TGO',
       'TKL', 'TON', 'TTO', 'TUN', 'TUR', 'TKM', 'TCA', 'TUV', 'UGA',
       'UKR', 'ARE', 'GBR', 'USA', 'OWID_UMC', 'URY', 'UZB', 'VUT', 'VAT',
       'VEN', 'VNM', 'WLF', 'OWID_WRL', 'YEM', 'ZMB', 'ZWE'], dtype=object)

In [106]:
# selecting row that starts with OWID iso_code
covid_continent_df = covid_dataset_df [covid_dataset_df['iso_code'].str.contains(r'(OWID\w)')!=False]

C:\Users\leona\anaconda3\lib\site-packages\pandas\core\strings\accessor.py:101: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return func(self, *args, **kwargs)

In [107]:
#checking the columns iso_code
covid_continent_df['iso_code'].unique()

array(['OWID_AFR', 'OWID_ASI', 'OWID_EUR', 'OWID_EUN', 'OWID_HIC',
       'OWID_INT', 'OWID_KOS', 'OWID_LIC', 'OWID_LMC', 'OWID_NAM',
       'OWID_CYN', 'OWID_OCE', 'OWID_SAM', 'OWID_UMC', 'OWID_WRL'],
      dtype=object)

In [108]:
covid_continent_df

,iso_code,continent,location,date,population,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
686,OWID_AFR,NaN,Africa,2020-02-13,1.373486e+09,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
687,OWID_AFR,NaN,Africa,2020-02-14,1.373486e+09,1.0,1.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
688,OWID_AFR,NaN,Africa,2020-02-15,1.373486e+09,1.0,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
689,OWID_AFR,NaN,Africa,2020-02-16,1.373486e+09,1.0,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
690,OWID_AFR,NaN,Africa,2020-02-17,1.373486e+09,1.0,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151431,OWID_WRL,NaN,World,2022-01-05,7.874966e+09,297770440.0,2506963.0,1886491.143,5465352.0,7748.0,...,6.434,34.635,60.13,2.705,72.58,0.737,NaN,NaN,NaN,NaN
151432,OWID_WRL,NaN,World,2022-01-06,7.874966e+09,300290277.0,2519837.0,1964838.714,5472566.0,6663.0,...,6.434,34.635,60.13,2.705,72.58,0.737,NaN,NaN,NaN,NaN
151433,OWID_WRL,NaN,World,2022-01-07,7.874966e+09,303164327.0,2874050.0,2136842.571,5479797.0,7231.0,...,6.434,34.635,60.13,2.705,72.58,0.737,NaN,NaN,NaN,NaN
151434,OWID_WRL,NaN,World,2022-01-08,7.874966e+09,305191603.0,2027276.0,2265657.571,5484782.0,4985.0,...,6.434,34.635,60.13,2.705,72.58,0.737,NaN,NaN,NaN,NaN
151435,OWID_WRL,NaN,World,2022-01-09,7.874966e+09,307155337.0,1963734.0,2422186.857,5488628.0,3846.0,...,6.434,34.635,60.13,2.705,72.58,0.737,NaN,NaN,NaN,NaN

In [109]:
#dropping columns

cols = [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 
        45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66]
newcnt_df = covid_continent_df.drop(covid_continent_df.columns[cols], axis=1)

In [110]:
newcnt_df

,iso_code,continent,location,date,population,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,...,new_deaths_smoothed_per_million,reproduction_rate,icu_patients,icu_patients_per_million,hosp_patients,hosp_patients_per_million,weekly_icu_admissions,weekly_icu_admissions_per_million,weekly_hosp_admissions,weekly_hosp_admissions_per_million
686,OWID_AFR,NaN,Africa,2020-02-13,1.373486e+09,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
687,OWID_AFR,NaN,Africa,2020-02-14,1.373486e+09,1.0,1.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
688,OWID_AFR,NaN,Africa,2020-02-15,1.373486e+09,1.0,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
689,OWID_AFR,NaN,Africa,2020-02-16,1.373486e+09,1.0,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
690,OWID_AFR,NaN,Africa,2020-02-17,1.373486e+09,1.0,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151431,OWID_WRL,NaN,World,2022-01-05,7.874966e+09,297770440.0,2506963.0,1886491.143,5465352.0,7748.0,...,0.757,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
151432,OWID_WRL,NaN,World,2022-01-06,7.874966e+09,300290277.0,2519837.0,1964838.714,5472566.0,6663.0,...,0.744,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
151433,OWID_WRL,NaN,World,2022-01-07,7.874966e+09,303164327.0,2874050.0,2136842.571,5479797.0,7231.0,...,0.769,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
151434,OWID_WRL,NaN,World,2022-01-08,7.874966e+09,305191603.0,2027276.0,2265657.571,5484782.0,4985.0,...,0.785,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
151435,OWID_WRL,NaN,World,2022-01-09,7.874966e+09,307155337.0,1963734.0,2422186.857,5488628.0,3846.0,...,0.800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [111]:
newcnt_df = newcnt_df.rename_axis('ind_cnt')
newcnt_df

,iso_code,continent,location,date,population,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,...,new_deaths_smoothed_per_million,reproduction_rate,icu_patients,icu_patients_per_million,hosp_patients,hosp_patients_per_million,weekly_icu_admissions,weekly_icu_admissions_per_million,weekly_hosp_admissions,weekly_hosp_admissions_per_million
ind_cnt,,,,,,,,,,,,,,,,,,,,,
686,OWID_AFR,NaN,Africa,2020-02-13,1.373486e+09,NaN,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
687,OWID_AFR,NaN,Africa,2020-02-14,1.373486e+09,1.0,1.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
688,OWID_AFR,NaN,Africa,2020-02-15,1.373486e+09,1.0,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
689,OWID_AFR,NaN,Africa,2020-02-16,1.373486e+09,1.0,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
690,OWID_AFR,NaN,Africa,2020-02-17,1.373486e+09,1.0,0.0,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151431,OWID_WRL,NaN,World,2022-01-05,7.874966e+09,297770440.0,2506963.0,1886491.143,5465352.0,7748.0,...,0.757,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
151432,OWID_WRL,NaN,World,2022-01-06,7.874966e+09,300290277.0,2519837.0,1964838.714,5472566.0,6663.0,...,0.744,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
151433,OWID_WRL,NaN,World,2022-01-07,7.874966e+09,303164327.0,2874050.0,2136842.571,5479797.0,7231.0,...,0.769,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
151434,OWID_WRL,NaN,World,2022-01-08,7.874966e+09,305191603.0,2027276.0,2265657.571,5484782.0,4985.0,...,0.785,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
151435,OWID_WRL,NaN,World,2022-01-09,7.874966e+09,307155337.0,1963734.0,2422186.857,5488628.0,3846.0,...,0.800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [112]:
# saving dataframe as csv file (continent)
newcnt_df.to_csv('Resources/covid_continent.csv', index=False)

# Creating dataframe for vaccinations

In [113]:
covid_dataset_df

,iso_code,continent,location,date,population,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-02-24,39835428.0,5.0,5.0,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-02-25,39835428.0,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-02-26,39835428.0,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-02-27,39835428.0,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-02-28,39835428.0,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153395,ZWE,Africa,Zimbabwe,2022-01-05,15092171.0,219057.0,1379.0,1644.143,5092.0,14.0,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
153396,ZWE,Africa,Zimbabwe,2022-01-06,15092171.0,220178.0,1121.0,1207.143,5108.0,16.0,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
153397,ZWE,Africa,Zimbabwe,2022-01-07,15092171.0,221282.0,1104.0,1146.286,5136.0,28.0,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
153398,ZWE,Africa,Zimbabwe,2022-01-08,15092171.0,221918.0,636.0,1100.571,5148.0,12.0,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
153399,ZWE,Africa,Zimbabwe,2022-01-09,15092171.0,221918.0,NaN,NaN,5148.0,NaN,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN

In [114]:
cols = [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]

newvac_df = covid_dataset_df.drop(covid_dataset_df.columns[cols], axis=1)

In [115]:
newvac_df = newvac_df.rename_axis('ind_vac')
newvac_df

,iso_code,continent,location,date,new_tests,total_tests,total_tests_per_thousand,new_tests_per_thousand,new_tests_smoothed,new_tests_smoothed_per_thousand,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
ind_vac,,,,,,,,,,,,,,,,,,,,,
0,AFG,Asia,Afghanistan,2020-02-24,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-02-25,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-02-26,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-02-27,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-02-28,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153395,ZWE,Africa,Zimbabwe,2022-01-05,6885.0,1734918.0,114.955,0.456,5848.0,0.387,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
153396,ZWE,Africa,Zimbabwe,2022-01-06,6048.0,1740966.0,115.356,0.401,5698.0,0.378,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
153397,ZWE,Africa,Zimbabwe,2022-01-07,6723.0,1747689.0,115.801,0.445,5780.0,0.383,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
153398,ZWE,Africa,Zimbabwe,2022-01-08,NaN,NaN,NaN,NaN,NaN,NaN,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
153399,ZWE,Africa,Zimbabwe,2022-01-09,NaN,NaN,NaN,NaN,NaN,NaN,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN

In [116]:
# saving dataframe as csv file (vaccinations)
newvac_df.to_csv('Resources/covid_vaccinations.csv', index=False)